[book]
authors = ["dirtmelon"]
language = "zh-CN"
src = "src"
title = "Knowledge"

[output.html]
default-theme = "light"
preferred-dark-theme = "Ayu"
git-repository-url = "https://github.com/dirtmelon/Knowledge"
git-repository-icon = "fa-github"
no-section-label = true

[output.html.fold]
enable = true
level = 0