name: Deploy

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  pages:
    name: GitHub Pages
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: actions/cache@v2
        id: cache
        with:
          path: |
            ~/.cargo/bin/mdbook
          key: ${{ runner.os }}-cargo-binary-mdbook
      - name: Install Rust (rustup)
        run: rustup update stable --no-self-update && rustup default stable
      - name: Install mdBook
        if: steps.cache.outputs.cache-hit != 'true'
        run: cargo install mdbook
      - name: Build book
        run: mdbook build
      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@releases/v3
        with:
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          BRANCH: gh-pages
          FOLDER: book

